# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/malaikasaleem944/malaika_flyrank/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

### Ranked action queue

The validated output is translated here into a ranked, human-reviewed action queue. Higher-priority items are not treated as guaranteed wins. Instead, the ranking is intended to help reviewers decide which content items appear most worth investigating first based on the measured signals and validated model output.

Each item receives:

* a **priority rank**, used to order review;
* a **recommended action**, describing the type of follow-up to consider;
* one or more **reason codes**, explaining why the item was placed in the queue;
* supporting signals, where available, to help a human reviewer inspect the recommendation.

### Reason codes

The queue uses interpretable reason codes rather than presenting a model score alone:

| Reason code                 | Interpretation                                                                               | Suggested review                                                                        |
| --------------------------- | -------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| `DECLINING_SIGNAL`          | The item shows a measured declining trend in the available historical data.                  | Investigate whether the decline is persistent and whether the content remains relevant. |
| `LOW_CTR_OPPORTUNITY`       | The item appears to receive visibility but has comparatively weak click-through performance. | Review title, snippet, search intent alignment, and content presentation.               |
| `AGING_CONTENT`             | The item has accumulated substantial content age and may warrant a freshness review.         | Check factual freshness, examples, references, and current relevance.                   |
| `POSITION_WITHOUT_CLICKS`   | Search visibility is present, but observed click performance appears relatively weak.        | Review search-result appeal and alignment with likely user intent.                      |
| `HIGH_PRIORITY_COMBINATION` | Multiple measured signals point toward the item being worth earlier review.                  | Perform a broader manual content audit before selecting an intervention.                |
| `INSUFFICIENT_EVIDENCE`     | The available signals are incomplete or ambiguous.                                           | Do not assign an automated content change; investigate manually or defer.               |

### Archetype-to-action mapping

The recommendation is based on the combination of observed signals, rather than assuming that one signal determines the correct intervention.

| Content archetype                           | Suggested action       | Human review question                                                        |
| ------------------------------------------- | ---------------------- | ---------------------------------------------------------------------------- |
| Declining and aging                         | `REFRESH_REVIEW`       | Is the content outdated, incomplete, or less aligned with current intent?    |
| Visible but low CTR                         | `SNIPPET_TITLE_REVIEW` | Could the title, description, or framing better represent the content?       |
| Declining with multiple weak signals        | `FULL_CONTENT_AUDIT`   | Is a broader update justified, or is there an external/seasonal explanation? |
| Older content with otherwise stable signals | `FRESHNESS_CHECK`      | Are facts, links, examples, and references still current?                    |
| Strong signals but ambiguous context        | `MANUAL_INVESTIGATION` | Is there enough contextual evidence to recommend any intervention?           |
| Missing or insufficient evidence            | `NO_AUTOMATED_ACTION`  | Should this item be deferred until more reliable information is available?   |

The resulting queue is therefore a **decision-support artifact**. It ranks items for human attention; it does not claim that applying a recommended action will cause traffic, ranking, or engagement to improve.

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

### Intended use

This action playbook is intended as a **decision-support tool** for prioritizing content review. Its primary users are analysts, editors, or content reviewers who need a structured way to decide which content items may deserve attention first.

The ranked queue combines the validated output with interpretable signals and reason codes. A higher-ranked item should be understood as a **higher-priority candidate for review**, not as a guaranteed opportunity or a prediction that a specific intervention will improve performance.

The playbook is intended to support questions such as:

* Which content items should a reviewer inspect first?
* Which measured signals contributed to the item's priority?
* What type of review may be appropriate for this content archetype?
* Where is the available evidence insufficient for a confident recommendation?

### Limits

This playbook has important limits:

1. **Decision-support, not autonomous action.** The output is designed to prioritize human attention. It should not directly trigger publishing, rewriting, deletion, URL changes, or other content changes.

2. **Observed patterns are not causal evidence.** The available data can show measured patterns and support ranking or flagging, but it does not establish that refreshing content, changing titles, or making another intervention will cause improved outcomes.

3. **Historical data may not represent future conditions.** Content performance, search behavior, competition, seasonality, and measurement conditions can change over time. A recommendation should therefore be reviewed in its current context.

4. **Reason codes simplify complex signals.** A reason code explains why an item entered the queue, but it does not capture every possible factor affecting content performance.

5. **Missing or ambiguous data limits confidence.** Items with incomplete or unclear signals should be flagged for manual investigation or assigned no automated action rather than receiving a strong recommendation.

6. **The ranking is portfolio-specific.** The validated output reflects patterns measured in the available FlyRank data and should not be assumed to generalize automatically to other datasets, portfolios, clients, or time periods.

7. **No guarantee of value or improvement.** A high rank means the item appears worth reviewing earlier under this decision-support framework. It does not mean that an intervention will increase traffic, clicks, rankings, or engagement.

For these reasons, the playbook should be used as a practical prioritization aid alongside human judgment, current content context, and appropriate editorial or business review.

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

### Human review rules

Every recommendation in the ranked queue requires human review before any content action is taken. The queue is designed to prioritize attention, not to make autonomous decisions.

Before acting on a recommendation, the reviewer should check:

1. **Current context:** Is the observed signal still relevant, or has the content already been updated since the measurement period?

2. **Content relevance:** Does the content still match the likely user or search intent?

3. **Freshness:** Are facts, examples, references, links, or other information outdated?

4. **Alternative explanations:** Could seasonality, measurement changes, external events, or other contextual factors explain the observed pattern?

5. **Recommendation evidence:** Do the reason codes and supporting signals provide enough evidence to justify review?

6. **Business or editorial importance:** Is the content appropriate for intervention, and are there strategic or editorial constraints that the ranking does not capture?

7. **Risk of the proposed action:** Could changing the title, content, URL, structure, or publication status create unintended consequences?

If the reviewer cannot explain why an item received its recommendation using the available signals, the item should be investigated further or deferred.

### No-go list: actions that should not be automated

The following actions should **not** be triggered automatically by this playbook:

* Automatic publishing of content changes.
* Automatic rewriting or generation of final content.
* Automatic deletion or unpublishing of content.
* Automatic URL, redirect, or site-structure changes.
* Automatic changes to titles, metadata, or other user-facing content.
* High-impact editorial or strategic decisions based only on the model score.
* Actions on items with missing, ambiguous, or insufficient evidence.
* Treating a high-ranked item as a guaranteed performance opportunity.
* Assuming that a recommended action will cause improvements in traffic, clicks, rankings, or engagement.

Items with the `INSUFFICIENT_EVIDENCE` or `NO_AUTOMATED_ACTION` outcome should remain outside automated workflows.

### Decision rule

The practical workflow is:

**Model or ranking output → reason codes → human review → contextual checks → human-approved action → later outcome monitoring**

The model output is therefore only the starting point for investigation. A human reviewer remains responsible for deciding whether an action is appropriate and for documenting any important context that the available data does not capture.

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

### Monitoring the action playbook

The recommendations should be monitored because the patterns used to create the ranked queue may become less representative over time. Monitoring is intended to identify when the playbook may need review; it is not an automatic production retraining system.

The following signals should trigger investigation:

| Trigger                                                 | What to check                                                                                    | Possible response                                                               |
| ------------------------------------------------------- | ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------- |
| Input data quality changes                              | Missingness, unexpected values, schema changes, or broken data pipelines                         | Pause or limit recommendations until the data issue is understood.              |
| Recommendation distribution shifts                      | A large change in the proportion of items assigned to particular actions or reason codes         | Review whether the underlying content portfolio or input patterns have changed. |
| Ranking quality weakens                                 | Validated ranking performance falls below the level considered useful in the previous evaluation | Re-evaluate the model and compare it with the baseline before reuse.            |
| New content patterns appear                             | New archetypes or combinations of signals are not well represented by the current action mapping | Update the archetype definitions and require additional human review.           |
| Recommendations become stale                            | Ranked items no longer reflect the current content state or have already been updated            | Regenerate the queue using the latest appropriate data.                         |
| Observed outcomes consistently differ from expectations | Human reviewers repeatedly find that recommendations are not useful or are poorly explained      | Audit features, reason codes, validation design, and action mapping.            |

### Retrain and review triggers

Retraining should be considered when there is evidence that the current model or ranking no longer provides useful decision support. Possible triggers include:

* substantial changes in the input data distribution;
* repeated data-quality or schema changes;
* degradation in validated out-of-sample performance;
* a sustained change in the types of content entering the portfolio;
* repeated human-review feedback showing that reason codes are unclear or recommendations are not practically useful;
* a planned review cycle using newly available data and the same leakage and validation checks used in the original model evaluation.

A retrain should **not** be triggered automatically only because a fixed amount of time has passed. Before replacing the current approach, the updated model should be evaluated against the existing baseline and validated using an appropriate split design.

### Monitoring boundaries

Monitoring should focus on whether the ranking remains useful as a prioritization tool. It should not interpret a lack of immediate performance improvement as proof that the model failed, because this project does not establish causal effects from specific content interventions.

The appropriate question is:

**Does the current evidence still support using this ranking to decide which content items deserve human review first?**

If the answer becomes unclear, the recommendations should be paused, reviewed, and revalidated before further use.

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

### Export plan

The ranked action queue will be regenerated by this notebook and written to `work/outputs/` so that the paper can use the same reproducible output.

The primary export is:

* `work/outputs/w07_ranked_action_queue.csv` — the ranked content-review queue with priority, recommended action, reason codes, and supporting signals.

The queue CSV is intentionally kept out of git because it contains row-level data. The notebook is the reproducible source for regenerating it.

Any report-ready figures will be saved separately under `work/figures/` and can be committed for reuse in the paper.

The export should contain enough information for a reviewer to understand **what was ranked, why it was ranked, and what type of human review is suggested**, without treating the recommendation as an automated action.

### Reproducibility note

The export is generated from the validated output already produced in the earlier workflow. No new model training or production deployment is performed in this notebook.

Before submission, the exported queue should be checked for:

* expected row count;
* required columns;
* priority ordering;
* reason-code coverage;
* missing or invalid values;
* absence of client-identifying or private information.

In [25]:
# Show the DataFrames currently available in the notebook
import pandas as pd

dataframes = {
    name: obj
    for name, obj in globals().items()
    if isinstance(obj, pd.DataFrame)
}

print("DataFrames currently available:")
for name, df in dataframes.items():
    print(f"- {name}: {df.shape}")

if not dataframes:
    print("No DataFrame is currently available.")

DataFrames currently available:
- df: (30000, 52)
- ranked_queue: (30000, 12)
- paper_queue: (12517, 11)

In [26]:
from pathlib import Path
import pandas as pd

# Find the repository root from the notebook's current location
current = Path.cwd()

candidates = [
    current,
    current.parent,
    current.parent.parent,
    current.parent.parent.parent
]

repo_root = None

for path in candidates:
    if (path / "data" / "raw" / "content_refresh_anonymized.csv").exists():
        repo_root = path
        break

if repo_root is None:
    raise FileNotFoundError(
        "Could not find data/raw/content_refresh_anonymized.csv. "
        f"Current working directory: {current}"
    )

DATA_PATH = repo_root / "data" / "raw" / "content_refresh_anonymized.csv"

df = pd.read_csv(DATA_PATH)

print("Repository root:", repo_root)
print("Dataset path:", DATA_PATH)
print("Dataset shape:", df.shape)

Repository root: c:\Users\Malaika Saleem\Documents\malaika_flyrank
Dataset path: c:\Users\Malaika Saleem\Documents\malaika_flyrank\data\raw\content_refresh_anonymized.csv
Dataset shape: (30000, 44)

In [27]:
# Create interpretable action signals

# A declining trend is used only as an action/review signal,
# not as a model feature.
df["declining_signal"] = df["trend_direction"].eq("declining")

# Older content may deserve a freshness review.
df["aging_signal"] = df["content_age_days"] >= 365

# Use a portfolio-relative CTR threshold.
# ctr is already expressed in percentage-point units in this dataset.
ctr_median = df["ctr"].median()

df["low_ctr_signal"] = (
    (df["ctr"] < ctr_median) &
    (df["impressions_90d"] > df["impressions_90d"].median())
)

# avg_position = 0 means no position data.
# Only valid positions are used here.
df["position_signal"] = (
    (df["avg_position"] > 0) &
    (df["avg_position"] <= 10) &
    (df["ctr"] < ctr_median)
)

# Count the number of supporting signals.
signal_cols = [
    "declining_signal",
    "aging_signal",
    "low_ctr_signal",
    "position_signal"
]

df["signal_count"] = df[signal_cols].sum(axis=1)

print("CTR median:", round(ctr_median, 3))
print("Items with at least one action signal:",
      int((df["signal_count"] > 0).sum()))

print("\nSignal counts:")
print(df[signal_cols].sum())

CTR median: 0.07
Items with at least one action signal: 12517

Signal counts:
declining_signal       0
aging_signal        6360
low_ctr_signal      3309
position_signal     5123
dtype: int64

In [28]:
# Check the actual values used in trend_direction
print("trend_direction values:")
print(df["trend_direction"].value_counts(dropna=False))

trend_direction values:
trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

In [29]:
# Correct declining signal based on the actual dataset values
df["declining_signal"] = df["trend_direction"].eq("down")

print("Declining items:", int(df["declining_signal"].sum()))

Declining items: 16262

In [30]:
def make_reason_codes(row):
    reasons = []

    if row["declining_signal"]:
        reasons.append("DECLINING_SIGNAL")

    if row["low_ctr_signal"]:
        reasons.append("LOW_CTR_OPPORTUNITY")

    if row["aging_signal"]:
        reasons.append("AGING_CONTENT")

    if row["position_signal"]:
        reasons.append("POSITION_WITHOUT_CLICKS")

    if not reasons:
        reasons.append("INSUFFICIENT_EVIDENCE")

    return "|".join(reasons)


def choose_action(row):
    if row["signal_count"] >= 2:
        return "FULL_CONTENT_AUDIT"

    if row["declining_signal"] and row["aging_signal"]:
        return "REFRESH_REVIEW"

    if row["position_signal"] or row["low_ctr_signal"]:
        return "SNIPPET_TITLE_REVIEW"

    if row["aging_signal"]:
        return "FRESHNESS_CHECK"

    return "NO_AUTOMATED_ACTION"


df["reason_codes"] = df.apply(make_reason_codes, axis=1)
df["recommended_action"] = df.apply(choose_action, axis=1)

print("Recommended actions:")
print(df["recommended_action"].value_counts())

Recommended actions:
recommended_action
NO_AUTOMATED_ACTION     17483
SNIPPET_TITLE_REVIEW     5509
FRESHNESS_CHECK          2931
FULL_CONTENT_AUDIT       2066
REFRESH_REVIEW           2011
Name: count, dtype: int64

In [31]:
# Create the ranked action queue

# Higher signal count = earlier human review.
# Impressions are used only as a secondary ordering signal.
# This is a review-priority ranking, not a prediction of improvement.

df["review_priority_score"] = df["signal_count"]

ranked_queue = (
    df.sort_values(
        ["review_priority_score", "impressions_90d"],
        ascending=[False, False]
    )
    .copy()
)

# Assign a unique 1-based priority rank
ranked_queue["priority_rank"] = range(1, len(ranked_queue) + 1)

# Select fields useful for human review and the paper
queue_columns = [
    "priority_rank",
    "client_id",
    "recommended_action",
    "reason_codes",
    "review_priority_score",
    "impressions_90d",
    "sessions_90d",
    "clicks_90d",
    "content_age_days",
    "avg_position",
    "ctr",
    "trend_direction"
]

ranked_queue = ranked_queue[queue_columns]

print("Ranked queue shape:", ranked_queue.shape)

print("\nTop 10 review candidates:")
display(ranked_queue.head(10))

Ranked queue shape: (30000, 12)

Top 10 review candidates:

,priority_rank,client_id,recommended_action,reason_codes,review_priority_score,impressions_90d,sessions_90d,clicks_90d,content_age_days,avg_position,ctr,trend_direction
25331,1,client_19581e27de,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,99013,134,31,419,6.4,0.03,down
12127,2,client_19581e27de,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,85120,202,50,389,6.7,0.06,stable
16657,3,client_19581e27de,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,73457,189,38,419,5.4,0.05,stable
2382,4,client_19581e27de,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,72631,20,12,482,6.5,0.02,down
3007,5,client_19581e27de,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,62990,114,36,445,8.4,0.06,stable
21782,6,client_19581e27de,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,51540,409,31,417,7.1,0.06,down
25137,7,client_3fdba35f04,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,43920,65,28,463,3.7,0.06,down
11163,8,client_4e07408562,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,43287,46,26,487,3.9,0.06,up
2945,9,client_19581e27de,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,39161,36,18,421,5.7,0.05,down
21823,10,client_19581e27de,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,32338,78,20,482,5.5,0.06,down

In [32]:
# Prepare the paper-facing queue.
# Client identifiers are excluded from the export.
# Items with actionable recommendations are ranked first.

actionable_actions = [
    "FULL_CONTENT_AUDIT",
    "REFRESH_REVIEW",
    "SNIPPET_TITLE_REVIEW",
    "FRESHNESS_CHECK"
]

paper_queue = ranked_queue[
    ranked_queue["recommended_action"].isin(actionable_actions)
].copy()

# Re-rank only actionable review candidates
paper_queue = paper_queue.sort_values(
    ["review_priority_score", "impressions_90d"],
    ascending=[False, False]
).copy()

paper_queue["priority_rank"] = range(1, len(paper_queue) + 1)

# Remove client identifier from the paper-facing export
paper_queue = paper_queue.drop(columns=["client_id"])

print("Actionable queue shape:", paper_queue.shape)

print("\nAction distribution:")
print(paper_queue["recommended_action"].value_counts())

print("\nTop 10 actionable review candidates:")
display(paper_queue.head(10))

Actionable queue shape: (12517, 11)

Action distribution:
recommended_action
SNIPPET_TITLE_REVIEW    5509
FRESHNESS_CHECK         2931
FULL_CONTENT_AUDIT      2066
REFRESH_REVIEW          2011
Name: count, dtype: int64

Top 10 actionable review candidates:

,priority_rank,recommended_action,reason_codes,review_priority_score,impressions_90d,sessions_90d,clicks_90d,content_age_days,avg_position,ctr,trend_direction
25331,1,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,99013,134,31,419,6.4,0.03,down
12127,2,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,85120,202,50,389,6.7,0.06,stable
16657,3,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,73457,189,38,419,5.4,0.05,stable
2382,4,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,72631,20,12,482,6.5,0.02,down
3007,5,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,62990,114,36,445,8.4,0.06,stable
21782,6,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,51540,409,31,417,7.1,0.06,down
25137,7,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,43920,65,28,463,3.7,0.06,down
11163,8,FULL_CONTENT_AUDIT,LOW_CTR_OPPORTUNITY|AGING_CONTENT|POSITION_WIT...,3,43287,46,26,487,3.9,0.06,up
2945,9,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,39161,36,18,421,5.7,0.05,down
21823,10,FULL_CONTENT_AUDIT,DECLINING_SIGNAL|LOW_CTR_OPPORTUNITY|AGING_CON...,3,32338,78,20,482,5.5,0.06,down

In [33]:
from pathlib import Path

# Create the output directory if it does not exist
output_dir = repo_root / "work" / "outputs"
output_dir.mkdir(parents=True, exist_ok=True)

# Export the actionable ranked queue
queue_path = output_dir / "w07_ranked_action_queue.csv"

paper_queue.to_csv(queue_path, index=False)

print("Exported:", queue_path)
print("Rows:", len(paper_queue))
print("Columns:", len(paper_queue.columns))

# Reproducibility checks
assert paper_queue["priority_rank"].is_unique
assert paper_queue["priority_rank"].min() == 1
assert paper_queue["priority_rank"].max() == len(paper_queue)

required_columns = [
    "priority_rank",
    "recommended_action",
    "reason_codes",
    "review_priority_score",
    "impressions_90d",
    "sessions_90d",
    "clicks_90d",
    "content_age_days",
    "avg_position",
    "ctr",
    "trend_direction"
]

assert all(col in paper_queue.columns for col in required_columns)

print("Export checks: PASS")

Exported: c:\Users\Malaika Saleem\Documents\malaika_flyrank\work\outputs\w07_ranked_action_queue.csv
Rows: 12517
Columns: 11
Export checks: PASS

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.